# Generated by Django 2.1.5 on 2019-02-05 18:15

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('mall', '0002_auto_20190127_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlObjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'список объектов',
                'verbose_name_plural': 'список объектов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MlObjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('buy_date', models.DateField(blank=True, verbose_name='дата приобретения')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', wagtail.core.fields.RichTextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MlObjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='mall.MlObjectPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall_mlobjecttag_items', to='taggit.Tag')),
            ],
            options={
                'verbose_name': 'ключ поиска',
                'verbose_name_plural': 'ключи поиска',
            },
        ),
        migrations.CreateModel(
            name='MlObjectTagIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mall.MlObjectTag', to='taggit.Tag', verbose_name='ключи поиска'),
        ),
    ]
