# Generated by Django 2.1.5 on 2019-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20190205_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlobjectpage',
            name='buy_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата приобретения'),
        ),
    ]
