# Generated by Django 2.1.5 on 2019-02-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20190205_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlobjectindexpage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mlobjectpage',
            name='name',
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='краткое описание'),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='краткое описание'),
        ),
    ]
