# Generated by Django 2.1.5 on 2019-02-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_auto_20190206_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlobjectindexpage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='краткое описание'),
        ),
    ]
