# Generated by Django 2.1.5 on 2019-02-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_auto_20190206_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlobjectpage',
            name='broken_parts_count',
            field=models.IntegerField(default=0, verbose_name='некритичных повреждений'),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='call_down',
            field=models.BooleanField(default=False, verbose_name='есть замечания'),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='critically_broken_parts_count',
            field=models.IntegerField(default=0, verbose_name='критичных повреждений'),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='diagnosed',
            field=models.BooleanField(default=True, verbose_name='осмотрен'),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='have_maintenance',
            field=models.BooleanField(default=True, verbose_name='обслужен'),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='have_to_be_repaired',
            field=models.BooleanField(default=False, verbose_name='требует ремонта'),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='is_critical',
            field=models.BooleanField(default=False, verbose_name='критически важен'),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='is_critically_broken',
            field=models.BooleanField(default=False, verbose_name='сломан'),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='включен'),
        ),
    ]
