# Generated by Django 2.1.5 on 2019-02-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_auto_20190206_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlobjectpage',
            name='subelements',
            field=models.IntegerField(default=0, verbose_name='составные части'),
        ),
    ]
