# Generated by Django 2.1.5 on 2019-02-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_mlobjectpage_subelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='broken_parts_count',
            field=models.IntegerField(default=0, verbose_name='некритичных повреждений'),
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='call_down',
            field=models.BooleanField(default=False, verbose_name='есть замечания'),
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='critically_broken_parts_count',
            field=models.IntegerField(default=0, verbose_name='критичных повреждений'),
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='diagnosed',
            field=models.BooleanField(default=True, verbose_name='группа осмотрена'),
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='have_maintenance',
            field=models.BooleanField(default=True, verbose_name='группа обслужена'),
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='have_to_be_repaired',
            field=models.BooleanField(default=False, verbose_name='требует ремонта'),
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='is_critical',
            field=models.BooleanField(default=True, verbose_name='группа критически важная'),
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='is_critically_broken',
            field=models.BooleanField(default=False, verbose_name='группа сломана'),
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='группа включен'),
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='subelements',
            field=models.IntegerField(default=0, verbose_name='составные части'),
        ),
    ]
