# Generated by Django 2.1.5 on 2019-02-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_auto_20190207_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='broken_if_all_elements_broken',
            field=models.BooleanField(default=False, verbose_name='группа сломана если все элементы сломаны'),
        ),
    ]
