# Generated by Django 2.1.5 on 2019-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_mlobjectindexpage_broken_if_all_elements_broken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlobjectindexpage',
            name='is_critical',
            field=models.BooleanField(default=True, verbose_name='группа критически важна'),
        ),
        migrations.AlterField(
            model_name='mlobjectindexpage',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='группа включена'),
        ),
    ]
