# Generated by Django 2.1.5 on 2019-02-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0014_mlobjectgalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlobjectgalleryimage',
            name='caption',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mlobjectgalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='фото'),
        ),
    ]
