# Generated by Django 2.1.5 on 2019-02-09 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0018_mlobjectindexpage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='mlcategory',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='название'),
            preserve_default=False,
        ),
    ]
