# Generated by Django 2.1.5 on 2019-02-09 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0020_auto_20190209_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlobjdisposer',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='MlObjStatus',
        ),
        migrations.RemoveField(
            model_name='mlcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='mlcategory',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='имя'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MlObjDisposer',
        ),
    ]
