# Generated by Django 2.1.5 on 2019-02-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('mall', '0022_auto_20190209_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlObjDisposer',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'распорядитель объекта',
                'verbose_name_plural': 'распорядители объектов',
            },
            bases=('wagtailcore.page',),
        ),
    ]
