# Generated by Django 2.1.5 on 2019-02-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('mall', '0024_mlobjectpage_disposer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlObjDisposerList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'спиок распорядителей',
                'verbose_name_plural': 'списки распорядителей',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='mlobjectpage',
            name='disposer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='распорядитель объекта'),
        ),
    ]
