# Generated by Django 2.1.5 on 2019-02-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0025_auto_20190209_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlobjectpage',
            name='buy_date',
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='начало'),
        ),
    ]
