# Generated by Django 2.1.5 on 2019-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0026_auto_20190209_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlobjectpage',
            name='status_ok',
            field=models.BooleanField(default=True, verbose_name='параметры в норме'),
        ),
    ]
