# Generated by Django 2.1.5 on 2019-02-10 23:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0028_disposerlibrary_mlobjectlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlobjdisposer',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='описание'),
        ),
    ]
