# Generated by Django 2.1.5 on 2019-02-11 17:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('mall', '0029_auto_20190210_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlObjectAutoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'состояние',
                'verbose_name_plural': 'состояние',
            },
        ),
        migrations.AlterField(
            model_name='mlobjectpage',
            name='is_critically_broken',
            field=models.BooleanField(default=False, verbose_name='авария'),
        ),
        migrations.AddField(
            model_name='mlobjectautotag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_tagged_items', to='mall.MlObjectPage'),
        ),
        migrations.AddField(
            model_name='mlobjectautotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall_mlobjectautotag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='auto_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='ml_obj_auto_tags', through='mall.MlObjectAutoTag', to='taggit.Tag', verbose_name='состояние'),
        ),
    ]
