# Generated by Django 2.1.5 on 2019-02-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0032_auto_20190217_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='is_visible_for_tags',
            field=models.BooleanField(default=True, verbose_name='группа видна для дочерних меток'),
        ),
    ]
