# Generated by Django 2.1.5 on 2019-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0034_auto_20190222_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlobjectpage',
            name='broken_parts_count',
        ),
        migrations.RemoveField(
            model_name='mlobjectpage',
            name='critically_broken_parts_count',
        ),
        migrations.RemoveField(
            model_name='mlobjectpage',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='mlobjectpage',
            name='sub_elements',
        ),
        migrations.AddField(
            model_name='mlobjectpage',
            name='install_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата установки'),
        ),
    ]
