# Generated by Django 2.1.5 on 2019-02-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0035_auto_20190222_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlobjectindexpage',
            name='broken_parts_count',
        ),
        migrations.RemoveField(
            model_name='mlobjectindexpage',
            name='critically_broken_parts_count',
        ),
        migrations.RemoveField(
            model_name='mlobjectindexpage',
            name='sub_elements',
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='full_cache_reset',
            field=models.BooleanField(default=False, verbose_name='полный сброс кэшированных данных'),
        ),
        migrations.AddField(
            model_name='mlobjectindexpage',
            name='partial_cache_reset',
            field=models.BooleanField(default=False, verbose_name='частичный сброс кэшированных данных'),
        ),
        migrations.AlterField(
            model_name='mlobjectindexpage',
            name='is_critical',
            field=models.IntegerField(default=0, verbose_name='критически важный элемент'),
        ),
        migrations.AlterField(
            model_name='mlobjectindexpage',
            name='is_critically_broken',
            field=models.IntegerField(default=0, verbose_name='сломано'),
        ),
    ]
