# Generated by Django 2.1.5 on 2019-02-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0036_auto_20190222_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlobjectindexpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mall.MlCategory'),
        ),
    ]
