# Generated by Django 2.1.5 on 2019-04-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0038_mlcategory_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlObjectAutoTagMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
